### ISSUE TITLE
gator grader command incorrect

### ISSUE THREAD

**Issue by colonc** [Allegheny-Computer-Science-111-F2017/cs111-F2017-lab-sheets#1]
Under the section of **Checking the Correctness of Your Program and Writing**, there are instructions regarding running the ./gatorgrader command. 

> To get started with the use of GatorGrader, type the command “./gatorgrader --start” in your
terminal window. Once this step completes you can type “./gatorgrader --check”. 

However the command should say `./gatorgrader.sh --start` and `./gatorgrader.sh --check`

**Comment by gkapfham** [comment]
Hello @colonc! Thanks for pointing out this problem in the assignment sheet. I have fixed it in a recent commit. You should now see that the `.sh` is appended to the end of the commands. For now, I am going to close this issue and mark it as resolved. Please let me know if the newest release of the assignment sheet does not fix the problem that you have mentioned.
