### ISSUE TITLE
Error in "Checking the Correctness of Your Program and Writing"

### ISSUE THREAD

**Issue by thomasv27** [Allegheny-Computer-Science-111-F2017/cs111-F2017-lab-sheets#2]
In lines 21-22 of the "Checking the Correctness of Your Program and Writing" section, in the description of the git commit command to type, there is an element missing.  It should read "type 'git commit src/main/java/labone/DisplayOutput.java' in your terminal." but the text is missing the "/java/" in between "/main/" and "/labone/."  I hope that explanation makes sense!

**Comment by gkapfham** [comment]
Hello @thomasv27! Thanks for pointing out this issue. I have resolved the incorrect directory name and fixed several of small issues in this assignment sheet. You can see that we have created a new release of the PDF which fixes all of the problems that you identified. If there are any other problems related to this issue, please comment here. For now, I am going to close this issue and mark it as resolved.
