### ISSUE TITLE
Lab Sheet Issue

### ISSUE THREAD

**Issue by thomasv27** [Allegheny-Computer-Science-111-F2017/cs111-F2017-lab-sheets#4]
In the "Checking the Correctness of Your Program and Writing" section of the Laboratory 2 sheet, it reads "For example, if you want to signal that the src/main/java/labtwo/
ComputeMoonDistance.java file is ready for transfer to GitHub you would first type “ git add src/
main/java/labone/DisplayOutput.java ” in your terminal."  This isn't right; it should say to type, well, "git add src/main/java/labtwo/ComputeMoonDistance.java"!!

**Comment by stapen** [comment]
I also found this issue. It seems like leftover code from lab one.

**Comment by gkapfham** [comment]
Hello @thomasv27 and @stapen! Thanks for pointing out this issue. I have resolved this small problem and you should see that the new versions of the lab assignment sheet no longer contain reference to an incorrect program. Let me know if you find any other mistakes!
